export const Currencies = [
  { code: "VND", name: "Vietnamese Dong (VND)" },
  { code: "USD", name: "United States Dollar (USD)" },
  { code: "EUR", name: "Euro (EUR)" },
  { code: "JPY", name: "Japanese Yen (JPY)" },
  { code: "GBP", name: "British Pound (GBP)" },
  { code: "AUD", name: "Australian Dollar (AUD)" },
  { code: "CAD", name: "Canadian Dollar (CAD)" },
  { code: "CHF", name: "Swiss Franc (CHF)" },
  { code: "INR", name: "Indian Rupee (INR)" },
  { code: "CNY", name: "Chinese Yuan (CNY)" },
  { code: "MYR", name: "Malaysian Ringgit (MYR)" },
  { code: "SGD", name: "Singapore Dollar (SGD)" },
  { code: "HKD", name: "Hong Kong Dollar (HKD)" },
  { code: "KRW", name: "South Korean Won (KRW)" },
  { code: "MXN", name: "Mexican Peso (MXN)" },
  { code: "BRL", name: "Brazilian Real (BRL)" },
  { code: "SEK", name: "Swedish Krona (SEK)" },
  { code: "NOK", name: "Norwegian Krone (NOK)" },
  { code: "DKK", name: "Danish Krone (DKK)" },
  { code: "ZAR", name: "South African Rand (ZAR)" },
];

// ChartOfAccount.js
export const ChartOfAccount = [
  { code: "111", name: "Cash", category: "Current Assets" },
  { code: "112", name: "Bank Deposits", category: "Current Assets" },
  { code: "113", name: "Money in Transit", category: "Current Assets" },
  {
    code: "121",
    name: "Investments Held to Maturity",
    category: "Current Assets",
  },
  {
    code: "131",
    name: "Receivables from Customers",
    category: "Current Assets",
  },
  { code: "133", name: "VAT Receivable", category: "Current Assets" },
  { code: "141", name: "Advances", category: "Current Assets" },
  {
    code: "142",
    name: "Short-term Prepaid Expenses",
    category: "Current Assets",
  },
  { code: "151", name: "Goods in Transit", category: "Current Assets" },
  { code: "152", name: "Raw Materials", category: "Current Assets" },
  { code: "153", name: "Tools and Supplies", category: "Current Assets" },
  { code: "154", name: "Work-in-progress Costs", category: "Current Assets" },
  { code: "156", name: "Merchandise", category: "Current Assets" },
  { code: "157", name: "Goods Sent for Sale", category: "Current Assets" },
  { code: "158", name: "Real Estate", category: "Current Assets" },
  { code: "161", name: "Short-term Loans", category: "Current Assets" },
  { code: "162", name: "Short-term Payables", category: "Current Assets" },
  {
    code: "211",
    name: "Tangible Fixed Assets",
    category: "Non-Current Assets",
  },
  { code: "212", name: "Intangible Assets", category: "Non-Current Assets" },
  { code: "213", name: "Work in Progress", category: "Non-Current Assets" },
  {
    code: "214",
    name: "Leased Fixed Assets",
    category: "Non-Current Assets",
  },
  {
    code: "221",
    name: "Investments in Subsidiaries",
    category: "Non-Current Assets",
  },
  {
    code: "222",
    name: "Investments in Associates",
    category: "Non-Current Assets",
  },
  {
    code: "223",
    name: "Other Long-term Investments",
    category: "Non-Current Assets",
  },
  { code: "311", name: "Equity", category: "Owner's Equity" },
  { code: "312", name: "Charter Capital", category: "Owner's Equity" },
  { code: "313", name: "Owner Contributions", category: "Owner's Equity" },
  { code: "314", name: "Retained Earnings", category: "Owner's Equity" },
  {
    code: "315",
    name: "Bonus and Welfare Funds",
    category: "Owner's Equity",
  },
  { code: "411", name: "Owner's Equity", category: "Liabilities" },
  { code: "412", name: "Financial Reserves", category: "Liabilities" },
  {
    code: "413",
    name: "Business Development Funds",
    category: "Liabilities",
  },
  {
    code: "414",
    name: "Investment and Development Funds",
    category: "Liabilities",
  },
  {
    code: "511",
    name: "Sales Revenue and Service Revenue",
    category: "Revenue",
  },
  { code: "512", name: "Sales of Goods", category: "Revenue" },
  { code: "513", name: "Service Revenue", category: "Revenue" },
  { code: "515", name: "Revenue from Asset Disposal", category: "Revenue" },
  { code: "516", name: "Other Revenues", category: "Revenue" },
  { code: "517", name: "Financial Revenue", category: "Revenue" },
  { code: "611", name: "Cost of Goods Sold", category: "Expenses" },
  { code: "612", name: "Selling Expenses", category: "Expenses" },
  { code: "621", name: "Production Costs", category: "Expenses" },
  { code: "622", name: "Administrative Expenses", category: "Expenses" },
  {
    code: "623",
    name: "Other Administrative Expenses",
    category: "Expenses",
  },
  { code: "625", name: "Interest Expenses", category: "Expenses" },
  { code: "627", name: "Administrative Fees", category: "Expenses" },
  { code: "631", name: "Labor Costs", category: "Expenses" },
  { code: "632", name: "Material Costs", category: "Expenses" },
  { code: "711", name: "Operating Profit", category: "Profit" },
  { code: "712", name: "Financial Profit", category: "Profit" },
  { code: "713", name: "Other Profit", category: "Profit" },
];
