name: ProdigyPM CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v4
    
    # 2. Cài đặt JDK (chuyển sang JDK 17 vì JDK 23 không phổ biến)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Temurin là bản JDK phổ biến
        cache: maven

    # 3. Build project với Maven
    - name: Build with Maven
      run: |
        cd server # Chuyển vào thư mục chứa code server
        mvn clean install
